### ISSUE TITLE
Request for Access to Environment Variables (dotenv) for Contribution

### ISSUE THREAD

**Issue by Pranavnk15** [rishyym0927/Affinity_frontend#1]
Hi,

I would love to contribute to your project, as the UI is fantastic and truly eye-catching! I've cloned the repository and have been exploring it in detail. However, I am facing an issue while trying to register and access the full functionality of the web app due to the absence of environment variables provided through the .env file.

Could you kindly provide the necessary dotenv variables so that I can set up the project locally and contribute more effectively?

Looking forward to contributing to the project!

Best regards,
Pranav

**Comment by rishyym0927** [comment]
Hey ! You do not need to setup the environment variables since this project is completely based on the frontend . I have added the sample data for the ease , you can modify those samples accordingly following the pattern. If you wish to contribute towards backend part of Affinity, the link of those project will be provided shortly within 1-2 days in readme.md
