### ISSUE TITLE
Integrate form validation rules for the registration process forms

### ISSUE THREAD

**Issue by Kp779** [rishyym0927/Affinity_frontend#18]
Problem: The registration form currently lacks proper validation rules which can lead to inconsistent data entry, security risks, and poor user experience. 

Expected Behavior:
When users fill out the registration form, the following validation rules should be enforced:

1. Name: Should not be empty and must be at least 3 characters long.
2. Email: Must be in a valid email format (e.g., name@example.com).
3. Password: Should be at least 8 characters long and secure.
4. Confirm Password: Must match the password entered.
5. Optional Fields (like Gender, etc.): Should provide proper validation and error handling when applicable.

Proposed Solution: 
1. Integrate real-time form validation in the frontend using React (or the relevant frontend framework).
2. Provide error messages that are user-friendly and help users correct their inputs.

Additionally:
Integrate checks in backend code to create a smooth and secure user experience.

**Comment by Kp779** [comment]
if the issue seems fair, please make the assignment so that I can start working on it.

**Comment by rishyym0927** [comment]
Hi @Kp779 ,

Thank you for highlighting the need for proper validation on the registration form. I have assigned this issue to you.

Please proceed with integrating real-time form validation in the frontend using React. Since this project currently lacks a backend, make sure to handle validation solely in the frontend. If you’d like to test it more thoroughly, you can set up a local backend for your own use, but please don’t include it in the project.

Let me know if you have any questions!
